import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import clsx from "clsx";
import { PageLoadProgressBar } from "@/components/common/PageLoadProgressBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, 'h-screen')}>
        <PageLoadProgressBar />
        <main className="h-full">{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
